from . import car_brand
from . import car_history
from . import res_partner
from . import car_service
from . import car_gear_box
from . import car_cylinder
from . import car_spec
from . import car_garage_reference
from . import car_color
from . import car_gear_type