from . import inspection_reject
from . import assign_team
from . import task_assign
from . import service_concern
from . import sale_warranty
from . import vehicle_register
from . import additional_part
from . import task_reset
from . import cancel_inspection
from . import additional_service
from . import advance_payment_wizard
from . import invoice_wizard
from . import warranty_applicable
