from . import crm
from . import vehicle_booking
from . import res_partner
from . import configurations
from . import vehicle_inspection
from . import checklist_template
from . import fleet
from . import health_report
from . import inspection_team
from . import project_task
from . import vehicle_job_card
from . import vehicle_product
from . import vehicle_inventory
from . import vehicle_res_config
from . import vehicle_account
from . import vehicle_warranty
from . import health_report_template
from . import vehicle_appointment
from . import res_company
from . import mail_activity
